### ISSUE TITLE
Fixtures 😩

### ISSUE THREAD

**Issue by MWSebastienT** [kresers/3W_Awards#19]
Fixture via un fichier csv permettant un remplissage facile pour le client 
- [x] Users
- [x] Agency
- [x] Blog
- [x] CategoryAwards
- [x] Customers
- [x] Parameters

**Comment by tfocqueu** [comment]
Fixtures : 

Awards
Category
Color
Contest
Country
Functionality
Tag
Technology
Website-type

**Comment by tfocqueu** [comment]
Issues done ! 

Updatable
